"""
class Tablename(AutogeneratedModel):

    class Meta:
        table_type = master | transaction
        table_schema = None
        concise_schema = None
        verbose_schema = None
        index_column = None
        column = ColumnSchema
"""
